var blogData = [{
      "id": 0,
      "date": '13th May 2019',
      "title": "Should a developer be using a CMS?",
      "subTitle": "Here I take a look at the advantages and disadvantages of using a CMS on the comparison between that and developing from scratch.",
      "intro": "Content management system’s are software application that runs on the web-server and allows a user to easily manage the content of their website. This uses an interface and does not require any programming knowledge to do. This makes it perfect for people who want to have a site that they can keep updated without having to learn to programme or pay a developer to update it for them.",
      "section1Header": "",
      "section1": "There are many CMS’s available today, all with various pros and cons. The most widely used however is WordPress. This dominates the CMS market being used by 59.9% of all known CMS websites (and there is a lot). It also accounts for a whopping 31.7% of all websites! (W3Techs.com, 1 September 2018)",
      "section2Header": "So how is this better than your own code?",
      "section2": "Developing websites from scratch is no easy feat, and many new developers want to prove to themselves and others that they can create anything and everything from scratch, this is good to learn but its also good to be aware that reinventing the wheel every time you have a new project can really slow you down. CMS have been developed for many years and if you want to make simple static advertisement websites or blogs then no matter your skill level you would be losing a lot of time and taking on a whole lot of extra work to produce a site similar to what a CMS can do for you.",
      "section3Header": "Why choose a CMS over doing it myself?",
      "section3": "1. The knowledge requirement. There is a low entry bar for CMS making development easy and adding the perk of allowing tech savvy clients to edit it themselves without any programming knowledge. 2. Plugins These can add all sorts of new capabilities to your site, and if it does not exist perhaps you can create your own! Reduced costs The lower development time, also has the added benefit of making the cost less for your customer. Templates, Templates, Templates! Every website starts with a template, this is what makes development time so much shorter. ",
      "section4Header": "So are there downsides?",
      "section4": "Maintenance In the wrong hands, an unmaintained and outdated CMS can do a lot of harm to a website and lead to serious security vulnerabilities. Adding content Although a user can add content them self doesn’t mean they should, the truth is writing content is a skill and unless they know how to do this or are willing to learn, it may end up to a good site becoming a bad one quickly. Adding complexity can get messy fast! if you try you can add a heck of a lot of features to your site via plugins and hacking away at the code. However just cause it works does not mean its the right tool for the job, and the result for using the wrong tool is usually a big fragile mess that a developer is hesitant to get involved with!",
      "section5Header": "",
      "section5": "There are many CMS’s available today, all with various pros and cons. The most widely used however is WordPress. This dominates the CMS market being used by 59.9% of all known CMS websites (and there is a lot). It also accounts for a whopping 31.7% of all websites! (W3Techs.com, 1 September 2018)",
      "section6Header": "",
      "section6": "",
      "conclusionHeader": "Conclusion:",
      "conclusion": "Yes! CMS are a great addition to a developers toolkit, but its important that a developer knows when and where to use them as using the wrong tool for the job can lead to further scalability issues down the line.",
      "postImage": require("../../images/blog-posts/cms/cms.jpg"),
      "imageCaption": "A snap of me attempting to work, up until the neighbourhood cat wandered in..",
      "referencesHeader": "References:",
      "references": ["https://w3techs.com/technologies/details/cm-wordpress/all/all"],
      "tags": ["CMS, ", "Websites, ", "Development, ", "WordPress"]
    }, 
    {
      "id": 1,
      "date": '22nd July 2019',
      "title": "Personal Update #1: Welcome to my blog!",
      "subTitle": "This is just a short introdcution to explain who I am and what I am trying to achieve with this site.",
      "intro": "My name is Jake French as you may have already guessed, I am website developer. I have worked with a variety of large companies and learnt a lot but never had a place to showcase this work properly before which is what got me started with this website.",
      "section1Header": "Why I started this website",
      "section1": "The primary reason I started this website was for a portfolio. Work projects, personal projects, Design ideas, all in one place. This is important in my line of work and especially as a contractor, as it allows me to quickly give people a taste of the type of work I do, and how I am able to help them reach their business/personal goals. The second reason was that I wanted to provide myself with a platform where I am able to talk about things I have learnt or just like and try and share this knowledge with other people out there who are interesed in similar things to me. The written word was never my forte althouh I always had interest in it, so I saw it as an oppurtinity to develop my writing skills also. Of course if anyone has any tips/suggestions for improving my blogging style I am always interested in learning more so please get in touch.",
      "section2Header": "Plans for the future",
      "section2": "Along with the things aforementioned I also want to cotinue to improve this website as a platform. My first plan for this will be to add a space for design work from sketches to full high fidelity mock ups of websites. In future blogs I will try to continue to mention my ideas/plans for further developing the site.",
      "section3Header": "",
      "section3": "",
      "section4Header": "",
      "section4": "",
      "section5Header": "",
      "section5": "",
      "section6Header": "",
      "section6": "",
      "conclusionHeader": "",
      "conclusion": "",
      "postImage": require("../../images/me.jpg"),
      "imageCaption": "A snap of me attempting to work, up until the neighbourhood cat wandered in..",
      "referencesHeader": "",
      "references": [],
      "tags": ["Future, ", "Plans"]
    }
]

export default blogData;